Zingle/ios-sdk

Pod/Classes/UI/Avatars/ZNGInitialsAvatar.h
Pod/Classes/UI/Avatars/ZNGInitialsAvatar.m

Sometimes you need previous avatars to make new avatars, 🐕

Added readonly properties to access the attributes of an initials avatar

---

Example/Tests/TestAccountSession.m
Pod/Classes/ZingleAccountSession.m

Zingle account sessions will no longer be marked as available/connected just before the current user information has been acquired from the API root.  Connection now only happens after the user info has been retrieved.
Added a unit test to ensure this.

SDK user info now available immediately on connection

---

Example/Tests/TestAccountSession.m
Example/Tests/mocks/ZNGMockUserClient.h
Example/Tests/mocks/ZNGMockUserClient.m
Example/ZingleSDK.xcodeproj/project.pbxproj
Pod/Classes/Clients/ZNGBaseClientAccount.h
Pod/Classes/Clients/ZNGBaseClientAccount.m
Pod/Classes/Clients/ZNGBaseClientService.h
Pod/Classes/Clients/ZNGUserClient.h
Pod/Classes/Clients/ZNGUserClient.m
Pod/Classes/Models/ZNGUser.h
Pod/Classes/Models/ZNGUser.m
Pod/Classes/UI/ViewModels/ZNGConversation.m
Pod/Classes/UI/Views/ZNGAvatarImageView.h
Pod/Classes/UI/Views/ZNGAvatarImageView.m
Pod/Classes/UI/Views/ZNGAvatarImageViewVerticallyCentered.h
Pod/Classes/UI/Views/ZNGAvatarImageViewVerticallyCentered.m
Pod/Classes/Utility/NSData+ImageType.h
Pod/Classes/Utility/NSData+ImageType.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

- Added ZNGUserClient to retrieve user data, including avatars, from the new /users/ end point
- Modified account session to wait until retrieving said user data before completing login
- Modified account session unit tests to check for the above
- Added avatar PUT/DELETE to ZNGUserClient
- Moved logic for determining image file type from the one place it was used (attaching images to messages) into an NSData category so that it can be used for avatar uploads
- Created an avatar UIImageView subclass that allows an optional icon to be superimposed over the avatar and handles both downloading remote images for avatars and using an initials avatar as a fallback

IOS-610: User avatar SDK support

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.h
Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.m
Pod/Classes/NetworkDiagnostics/ZNGReachability.h
Pod/Classes/NetworkDiagnostics/ZNGReachability.m
Pod/Classes/UI/Categories/UILabel+NetworkStatus.h
Pod/Classes/UI/Categories/UILabel+NetworkStatus.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

http://jira.zinglecorp.com:8080/browse/IOS-479
- Added a network lookout class to monitor connection status and diagnose healthy vs. no internet connection vs. API unreachable vs. socket connection itself is misbehaving.
- Added a UILabel extension to set network status text consistently in any view that wishes to do so
- Added that UILabel to the conversation views.

IOS-479: Socket connection monitoring and network status text

---

Pod/Classes/UI/Views/ZNGLabelCollectionViewCell.m
Pod/Classes/UI/Views/ZNGLabelGridView.m

http://jira.zinglecorp.com:8080/browse/IOS-618
Stopped lightening the background color and using the background color as text color.  Now text color (and border color) are text color, and background color is background color.
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;🖌 
🎨

IOS-618: Trust the server regarding label colors again

---

Pod/Classes/UI/Categories/UIColor+ZingleSDK.h
Pod/Classes/UI/Categories/UIColor+ZingleSDK.m
Pod/Classes/UI/Categories/UILabel+NetworkStatus.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/Views/ZNGPaddedLabel.h
Pod/Classes/UI/Views/ZNGPaddedLabel.m

http://jira.zinglecorp.com:8080/browse/IOS-479
- Added some vertical padding for a less scrunched label
- Changed background color to dark blue (instead of puke red and puke orange)
- Changed wording
💬  
&nbsp;&nbsp;&nbsp;&nbsp;🔧  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;👨‍🎨

IOS-479: Visual tweaks to network status message

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

http://jira.zinglecorp.com:8080/browse/IOS-629
Viewing a conversation that was locked due to automation, leaving it, viewing another conversation, and returning to the first conversation no longer shows the conversation as locked by automation, even though the message controls are locked appropriately.
The automation banner is now shown or hidden in viewDidLoad.
&nbsp;
&nbsp;
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;🖌 
🤖❔

IOS-629: Fix occasionally invisible automation-in-progress banner

---

Pod/Classes/UI/Layout/ZNGBubblesSizeCalculator.m

http://jira.zinglecorp.com:8080/browse/IOS-631
Apparently the NSStringDrawingUsesDeviceMetrics flag for doing string size calculations would return 0 x 0 for certain strings in iOS 8.  This must have been an iOS bug, as the behavior is correct in iOS 9 and iOS 10.
If iOS 8 is detected at run time, we will no longer use that flag, resulting in message bubbles that are occasionally slightly larger than they need to be.
We will probably axe iOS 8 support some time in the near future, but there's no need to do so for this issue.
&nbsp;
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;🅰️
📏   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🤔

IOS-631: Handle an iOS 8 bug that causes text render size to be 0x0

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

http://jira.zinglecorp.com:8080/browse/IOS-632
The robot emoji was added in iOS 9.1.  We use this emoji to indicate an active automation and as the outgoing message avatar for automatic responses.  These non-existent robots in iOS 9.0 and earlier are now satellite dishes instead of silly question marks.
&nbsp;
&nbsp;
❓ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;➡️  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖 🤖

IOS-632: No robot (emojis) allowed in iOS 9.0 or earlier

---

Pod/Classes/Models/ZNGEvent.h
Pod/Classes/Models/ZNGEvent.m
Pod/Classes/Models/ZNGMessage/ZNGMessage.h
Pod/Classes/Models/ZNGMessage/ZNGMessage.m
Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/Layout/ZNGBubblesSizeCalculator.m
Pod/Classes/UI/ViewModels/ZNGConversation.h
Pod/Classes/UI/ViewModels/ZNGConversation.m
Pod/Classes/UI/ViewModels/ZNGConversationServiceToContact.m

http://jira.zinglecorp.com:8080/browse/IOS-647
Notes now behave like outgoing messages; the user cannot send replies nor use templates/custom fields while a note is being sent.  The note will also display while sending as messages already do.
:shipit: ✏️  🗒

IOS-647: Block user input while a note is outbound

---

Pod/Classes/UI/ViewModels/ZNGConversation.h
Pod/Classes/UI/ViewModels/ZNGConversationServiceToContact.m

http://jira.zinglecorp.com:8080/browse/IOS-648
Do not merge this before https://github.com/Zingle/ios-sdk/pull/40 ❗️ ❗️ 
User meta data will now be attached to the local versions of sending messages/notes, allowing the UI to display avatars.  Previously, the avatar would be the user's initials until the server actually accepted and responded to the message, at which time the avatar would appear.
☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ 
☁️ ☁️☁️ ☁️☁️ ☁️ &nbsp;&nbsp;&nbsp;&nbsp;😲 &nbsp;&nbsp;&nbsp;&nbsp; ☁️ ☁️☁️ ☁️☁️ ☁️☁️ 
☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️☁️ ☁️

IOS-648: Avatars on outgoing messages/notes

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.h
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

http://jira.zinglecorp.com:8080/browse/IOS-647
The UUID sent with messages to prevent duplicates was not being reset when inserting a custom field nor a template.  This caused messages that consisted solely of one or the other to be ignored by the server after a note was sent.
Note: The reproduction steps do not work if the user then inserts a single space or edits the template/custom field in any way before hitting send, since this resets the UUID.
👻  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;& …

IOS-647: Fixed ghost messages due to stale UUIDs

---

Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

- Replaced open/closed boolean with an open/closed/both enumeration.  This will allow the same data set objects to be used to populate contacts tab data (where we do not care if a contact has an open conversation or not.)
- Added a `@noescape` attribute to the builder block to quash circular reference warnings when used in Swift

Inbox data allowing open/closed/both filtering

---

Pod/Classes/UI/Views/ZNGEditContactFooter.xib
Pod/Classes/UI/ZNGConversation.storyboard

- Stopped a table section footer that is used for spacing from obscuring a tiny sliver of content on the bottom of the contact edit screen
- Resolved some auto layout constraint warnings

Small layout issues on contact edit screen

---

Pod/Classes/UI/Avatars/ZNGInitialsAvatar.h
Pod/Classes/UI/Avatars/ZNGInitialsAvatar.m
Pod/Classes/UI/Views/ZNGAvatarImageView.h

A null initials string will render an empty circle for the initials avatar.
⚪️  😕

Allow null initials string for initials avatar

---

Example/Tests/TestInboxDataSet.m
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

- Moved page size to immutable, readonly property set via builder
- Stopped sending 'false' for search_message_bodies, because the API interprets 'false' as HE SAID SOMETHING SO HE MUST WANT IT.
💢

Added page size to inbox data builder, stopped always searching message bodies

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

This had been seen once or twice (never in the wild.)  Some upcoming changes to add skeleton loading views made this crash easily reproducible.  Sometimes the view hierarchy could be loaded while the values for message cell identifier were still set to the original, superclass value.  Moving the setting of these values up in the load process solved the problem.
⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️  🆙  ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ ⬆️ 
https://youtu.be/ufw9dVys3t0

Fixed an incorrect cell type crash

---

Pod/Classes/Models/ZNGMessage/ZNGMessage.h
Pod/Classes/Models/ZNGMessage/ZNGMessage.m
Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/Controllers/ZNGImageViewController.h
Pod/Classes/UI/Controllers/ZNGImageViewController.m
Pod/Classes/UI/Controllers/ZNGImageViewController.xib
Pod/Classes/UI/Layout/ZNGBubblesSizeCalculator.m
Pod/Classes/UI/Layout/ZNGImageSizeCache.m
Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.h
Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.m
ZingleSDK.podspec

http://jira.zinglecorp.com:8080/browse/IOS-649
Changed from stupidly downloading every image attachment in order as soon as it appeared in data and not really caching anything to using the SDWebImage library to display images on demand with caching.
💁‍♂️ 📷  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↔️ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 💾

IOS-649: Smarter image displaying

---

Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m

Contacts with no message history were showing up in the total contacts list, but they were not showing up when a search term was typed.  This was due to a bug in the contact data set builder copying code.

Contact search fix for contacts with no messages

---

Pod/Classes/UI/Views/ZNGConversationTextView.h
Pod/Classes/UI/Views/ZNGConversationTextView.m
Pod/Classes/UI/Views/ZNGConversationToolbarContentView.h
Pod/Classes/UI/Views/ZNGConversationToolbarContentView.m
Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.h
Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.m

:warning: https://github.com/Zingle/ios-business-app/pull/67 should be merged before this PR. :warning:
http://jira.zinglecorp.com:8080/browse/IOS-676
Added a hideCursor property to text view subclass.  Use it if the user expands input buttons and if they return via touch or text input.
🥇

IOS-676: Hiding text input cursor if user presses input buttons

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

http://jira.zinglecorp.com:8080/browse/IOS-678
✏️

IOS-678: Canceling internal note no longer returns input to text field

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.h

This was never used in the business app; it was only very briefly used by contact API users, e.g. Four Seasons prototype usage.

Removed old, invisible marking message as read

---

Pod/Classes/UI/ViewModels/Events/ZNGConversation.m

http://jira.zinglecorp.com:8080/browse/IOS-688
Events that happen simultaneously now appear in a more sane order.  (Example: Incoming message, keyword automation started, reply send, keyword automation ended)

IOS-688: Added top level sort direction to event queries to allow tie breaking

---

Pod/Classes/UI/Views/ZNGLabelGridView.m

http://jira.zinglecorp.com:8080/browse/IOS-699
Made some small changes to the label grid to better handle a view that changes sizes after initial rendering, such as within a UITableViewCell on an iPad.

IOS-699: Fix an iPad tag/segment grid overflow

---

Pod/Classes/Clients/ZNGNotificationsClient.m
Pod/Classes/Models/ZNGNotificationRegistration.h
Pod/Classes/Models/ZNGNotificationRegistration.m

Devices can now specify either dev (sandbox) or production push certificates be used when pushing data to them.  This choice is based on whether the app itself was signed with a development or production distribution certificate.  We'll check for a `DEBUG` preprocessor value on compile and choose from there.

Added push environment specification to push registrations

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/Models/ZNGUser.h
Pod/Classes/Models/ZNGUser.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.h
Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
Pod/Classes/UI/ZNGConversation.storyboard

http://jira.zinglecorp.com:8080/browse/IOS-693
Updated the typing indicator/collision detector to use the new `userIsReplying` socket event instead of the old `feedLocked` and `feedUnlocked` events.  Those will continue to work to handle users typing in the old UI, but iOS users typing will no longer send those events, so only new UI users will see notifications for iOS users typing.

IOS-693: Typing indicator changes

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

The initial attempt at this fix manually set the contentInset values for the conversation collection view.  Apparently there is a `topContentAdditionalInset` property in the message UI library we use that handles this much more reliably and does not break on device rotation.

IOS-681: Top banners obscuring top text in conversations

---

Pod/Classes/UI/ZNGConversation.storyboard

The banner indicating an automation in progress would disappear on iPhones if the user rotated the device.  Apparently `installed` != `active` when it comes to `NSLayoutConstraint`.

IOS-714: iPhone automation banner rotation issue fix

---

Pod/Classes/Models/ZNGEvent.h
Pod/Classes/Models/ZNGEvent.m
Pod/Classes/Models/ZNGMessage/ZNGMessage.h
Pod/Classes/Models/ZNGMessage/ZNGMessage.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.m

When data arrived indicating a delayed message had been sent, the new data was being ignored because events were treated as immutable.  Message with isDelayed set (either in new or old data) will now be checked for changes when data including them arrives.

IOS-689: Delayed messages that have been sent will now be updated

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

'Select a channel' will be displayed instead of an ominously empty channel selection.  The input is locked until a channel is selected.

IOS-717: Handle disappearing active channel

---

Pod/Classes/Models/ZNGContact/ZNGContact.m
Pod/Classes/Models/ZNGContactGroup.m
Pod/Classes/UI/Controllers/ZNGInboxViewController.m
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

Any push notification regarding the current service will now cause inbox data to refresh (thus displaying any changes to segments) and will update any changed contact data that is cached in conversation objects.

IOS-679: Contact/segment updates via push notifications

---

Pod/Classes/Models/ZNGContactGroup.m

http://jira.zinglecorp.com:8080/browse/IOS-724
Null tag/segment colors sent by the server were eventually turning from gray to yellow due to a bug in serializing grayscale colors into HTML codes.

IOS-724: Stopped peeing on grayscale colors when serializing them

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

http://jira.zinglecorp.com:8080/browse/IOS-727
Attaching more than one image in a row would not reset the hidden UUID, causing the server to discard future messages as duplicates.

IOS-727: Fix vanishing subsequent image attachments

---

Pod/Classes/UI/Controllers/ZNGContactEditViewController.h
Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
Pod/Classes/UI/Controllers/ZNGLabelSelectViewController.h
Pod/Classes/UI/Controllers/ZNGLabelSelectViewController.m
Pod/Classes/UI/ZNGConversation.storyboard

http://jira.zinglecorp.com:8080/browse/IOS-712
Using `UINavigationBar`s outside of `UINavigationController`s was causing positioning and sizing issues when build with the iOS 11 SDK.  These were only used for appearances, so they were easy to replace with plain views.

IOS-712: Replace UINavigationBars with plain ol' views

---

Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
Pod/Classes/UI/ZNGConversation.storyboard

http://jira.zinglecorp.com:8080/browse/IOS-707
Automatic table row sizing was not setup correctly and was breaking when built with the iOS 11 SDK.

IOS-707: Fixed iOS 11 edit contact row sizing

---

Pod/Classes/UI/Controllers/ZNGContactEditViewController.m

The fix for building with the iOS 11 SDK in https://github.com/Zingle/ios-sdk/pull/101 caused a regression when built with the iOS 10 SDK.  This fixes it with a row sizing logic compromise.

IOS-707: Fixed a contact edit table row regression 

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

https://zingle.atlassian.net/browse/IOS-740
Fixed a crash if a `}` character is deleted with a `{` character somewhere later in the text.  How silly.

IOS-740: Open and close brace confusion crash

---

Example/Tests/TestAccountSession.m
Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/Models/ZNGUser.m
Pod/Classes/Models/ZNGUserAuthorization.h
Pod/Classes/Models/ZNGUserAuthorization.m
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

The user object retrievable at the base URL of the API should now include all information we used to acquire through /users/.  To avoid some auth problems with users across different accounts (https://zingle.atlassian.net/browse/IOS-737), the separate requests to /users/ have been removed.  SDK users can either obtain this information from the `ZNGUserAuthorization` object or the convenience constructor that can make a `ZNGUser` from a `ZNGUserAuthorization` object.

Replaced ZNGUser with ZNGUserAuthorization

---

Pod/Classes/Clients/ZNGBaseClient.m
Pod/Classes/Clients/ZNGHotsosClient.m
Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/Clients/ZNGUserClient.h
Pod/Classes/Clients/ZNGUserClient.m
Pod/Classes/Models/ZNGError.m
Pod/Classes/UI/Categories/UIColor+ZingleSDK.h
Pod/Classes/UI/Controllers/ZNGConversationViewController.h
Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/ZingleContactSession.h
Pod/Classes/ZingleContactSession.m
Pod/Classes/ZingleSession.m
ZingleSDK.podspec

Cleaned up some Xcode 9 warnings regarding documentation comments and block declarations and switched to a more specific subspec of AFNetworking to avoid similar warnings in its UI tools.

Warning cleanup

---

Pod/Classes/UI/Views/ZNGConversationTextView.m

https://zingle.atlassian.net/browse/IOS-747
You have to love discovering a button in your app that causes a crash 100% of the time when pressed and has been around forever.

IOS-747: Removed "delete" button that really meant "crash"

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

iOS no longer asks a user to grant permission when an app first browses the photo library; the user is asked permission only after an image is selected for the app to use.
This change and our usage of `PHImageManager` caused the very first image attachment after a fresh install to fail on iOS 11 at the same time as access to the photo library was requested.

IOS-748: Update for iOS 11 photo library permission changes

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

https://zingle.atlassian.net/browse/IOS-746
The `UIImagePickerController` documentation says that this is required, though it mostly worked as a modal view previously.  This change will avoid IOS-746's odd landscape/portrait issue on iPad.

IOS-746: Changed photo picker to popover

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

https://zingle.atlassian.net/browse/IOS-744
Something magical and mysterious was restoring normal 1.0 alpha to message cells, breaking the intentionally transparent delayed message cells.  These cells now make their backgrounds transparent instead of the entire cell, avoiding whatever ghost was restoring their opacity.

IOS-744: Fixed an inconsistent transparency issue with delayed messages

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m

https://zingle.atlassian.net/browse/IOS-750
Regression from https://github.com/Zingle/ios-sdk/pull/116

IOS-750: Restored faded appearance of delayed image messages

---

Pod/Classes/Models/ZNGChannelType.h
Pod/Classes/Models/ZNGChannelType.m
Pod/Classes/UI/Controllers/ZNGContactEditViewController.m

https://zingle.atlassian.net/browse/IOS-506
Only channel values of `typeClass` `PhoneNumber` or `EmailAddress` will be editable in the contact edit UI.

IOS-506: Prevent editing Facebook/etc. channel values

---

Pod/Classes/UI/ViewModels/Events/ZNGConversation.m

Yes, Xcode, I know that selector is not available in iOS 9.  That's why I checked if the selector was available before I called it.
Have it your way.

Tiny warning go squish

---

Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m

https://zingle.atlassian.net/browse/IOS-757
On physical iOS 11 devices, date custom fields were being set to the human readable string like `05/07/1985` instead of the expected epoch timestamp.  How silly.

IOS-757: Fixed date custom field saving

---

Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m

Apparently Russian localization settings do not play well with using UTC as a time zone.  How very Пиндос of me to think that it would.

IOS-757: Silly Russian date fix

---

Pod/Classes/Clients/ZNGHotsosClient.m

The API used to just send us a host name and path.  Now it sometimes enjoys sending http:// for a host name where we would like to use https:// anyway.  You can't tell us what to do, server.

IOS-758: More tolerant Hotsos API URL handling

---

Pod/Classes/UI/Views/ZNGTableViewCell.m

Inbox table cell swipe actions no longer interfere with screen edge gestures (such as are used in the new left menu for teams/settings)

More gentle swipes

---

Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

https://zingle.atlassian.net/browse/IOS-767
Fixed a bug that caused an temporary internet connectivity problem to forever break inbox refreshing.

IOS-767: Internet busto should not mean app busto

---

Pod/Classes/Models/ZNGUser.h
Pod/Classes/Models/ZNGUser.m
Pod/Classes/Models/ZNGUserAuthorization.h
Pod/Classes/Models/ZNGUserAuthorization.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
Pod/Classes/ZingleAccountSession.m

- Added parsing of user privilege data that is now available in the API
- Users with the `monitor_teams` privilege will now see all teams in the left menu
- Changed the mostly redundant `ZNGUserAuthorization` class to be a simple subclass of `ZNGUser` with one additional field

Admins see all teams

---

Pod/Classes/UI/Views/Contact Editing/ZNGContactEditFloatLabeledTextField.m
Pod/Classes/UI/Views/ZNGNonLeakingTextField.h
Pod/Classes/UI/Views/ZNGNonLeakingTextField.m
Pod/Classes/UI/ZNGConversation.storyboard

Please, `UITextField`s, stop doing that.

Prevented UITextFields from leaking themselves

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

This one place was missed when showing/hiding assignment options.  Oops.

Remove the "assign" option from services with no assignment

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

One more implicit self capture fix

---

Pod/Classes/Models/ZNGEvent.m

https://zingle.atlassian.net/browse/IOS-805
This also fixes "by (null) being shown for every single automation event that lacked a triggeredByUser name.

IOS-805: Fix assignment event descriptions for automation assignments

---

Example/Tests/TestAccountSession.m
Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m
Pod/Classes/ZingleAccountSession.m

- Sessions are no longer marked active before they have full team/user data
- Added a method in `ZNGInboxDataSetBuilder` to check the validity of an inbox filter in a specific service
Facilitates https://zingle.atlassian.net/browse/IOS-798 through other changes in the business app.

IOS-798: Require full team/user data before session is usable

---

Pod/Classes/ZingleAccountSession.m

Apparently socket clients need to be manually disconnected.  Who knew?

IOS-810: Actually disconnect socket

---

Pod/Classes/UI/Controllers/ZNGContactEditViewController.h
Pod/Classes/UI/Controllers/ZNGContactEditViewController.m

https://zingle.atlassian.net/browse/IOS-811
The transition from the contact view was the bad kind of goofy.

IOS-811: Added a flag to edit contact to avoid custom transitions

---

Pod/Classes/UI/Controllers/ZNGInboxViewController.m

https://zingle.atlassian.net/browse/IOS-810
There was a retain cycle in the swipe action buttons that caused the inbox view to hang around and keep hold of a session object and its socket client forever.

IOS-810: More leaky socket fixes

---

Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m

https://zingle.atlassian.net/browse/IOS-815
Contact data was only being automatically refreshed if it existed within an active `ZNGInboxDataSet`.  The `ZNGContact` objects themselves will now refresh when receiving a relevant `feedUpdated` event from socket.

IOS-815: More contact refreshing

---

Pod/Classes/Clients/ZNGSocketClient.m

https://zingle.atlassian.net/browse/IOS-817
Why does it have to be null, socket?  I thought we had a good thing going.

IOS-817: Fixed a crash when sending group messages

---

Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

This can be used to determine if an inbox data change indicates switching between open/close in the same type of inbox or if it represents an entirely new type of inbox (team A vs. unassigned, etc.).

Added a method to compare two types of inbox data while ignoring open/closed

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

https://zingle.atlassian.net/browse/IOS-824
This logic was relying on a magic "in automation:" string that is no longer present.  We will no longer rely on magic strings in the description.

IOS-824: Fix locked by automation banner

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
Pod/Classes/ZingleAccountSession.m
Pod/Classes/ZingleContactSession.m
Pod/Classes/ZingleSession.m

https://zingle.atlassian.net/browse/IOS-826
Some notifications very rarely have integers where strings are expected.  Using the string specific equality method caused us to explode.  We will use the slightly less efficient `isEqual` to avoid crashes from unsanitized data.

IOS-826: Better tolerate stupid server data

---

Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

https://www.fabric.io/zingle/ios/apps/com.zingleme.zingle/issues/59c40f1abe077a4dcc03b1be
https://www.fabric.io/zingle/ios/apps/com.zingleme.zingle/issues/5a316fcc8cb3c2fa63ccf905
https://www.fabric.io/zingle/ios/apps/com.zingleme.zingle/issues/5a8a117c8cb3c2fa6356586b
Removed a rather precise calculation for insertion range that rarely causes a crash.  The trade off is that multiple Key Value Observing notifications will now be sent when multiple contacts arrive at once.  This should have no visible downside.

Hopefully fixed a data merging crash that has haunted the app forever

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

Replaced error-prone insert and delete calls with `reloadSections:` that will not crash if timing is weird vs. the superclasses' refresh logic.

Fixed a typing indicator crash

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.h
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/Transitions/ZNGEditContactExitTransition.m
Pod/Classes/UI/Transitions/ZNGEditContactTransition.m

Shortening a contact's name caused a crash.  Yeah.

IOS-828: Name shortening crash

---

Example/Tests/TestInboxStatistician.m
Pod/Classes/UI/ViewModels/Inbox Badges/ZNGInboxStatistician.m

https://zingle.atlassian.net/browse/IOS-831
Mobile users on services with assignment enabled were seeing incorrect in-app badge numbers due to this bug.

Fix badge numbers for assigned conversations

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/Models/ZNGUser.h
Pod/Classes/Models/ZNGUser.m
Pod/Classes/Models/ZNGUserSettings.h
Pod/Classes/Models/ZNGUserSettings.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

- Added `settings` to `ZNGUser`
- Made both view settings, `showOnlyMyTeammates` and `showUnassignedConversations`, default to `true` if unspecified
- Added a method to retrieve only users that share at least one team with the current user (to facilitate `showOnlyMyTeammates`

Added user settings for inboxes/users display

---

Pod/Classes/ZingleAccountSession.m

... in the user's settings (and if assignment is enabled)

Stop counting unassigned for badge number if unassigned inbox is disabled

---

Pod/Classes/UI/Transitions/ZNGEditContactTransition.m

The conversation view is not necessarily full width.  Oops.  Let's take that into account.

Fix edit contact name animation bug on iPad

---

Pod/Classes/ZingleSession.m

Push notifications were discarded as Zingle-irrelevant if their category was not exactly "Zingle".  We now check for anything _beginning_ with "zingle".

Recognize multiple push notification categories

---

Pod/Classes/Models/ZNGContact/ZNGContact.h
Pod/Classes/Models/ZNGContact/ZNGContact.m

Adding background close/mark read/reply actions means we need a positive response to allow error reporting on failures.

Added close/confirm methods with completion blocks

---

Pod/Classes/Models/ZNGUserSettings.h
Pod/Classes/Models/ZNGUserSettings.m

iOS was defaulting to showing only users who share a team with the current user if the user had never selected either option in My Settings.  Web did the opposite.  Now iOS will be more webby.

IOS-838: Adjusted user settings defaults to match web

---

Pod/Classes/UI/ViewModels/Events/ZNGConversation.m

A private method, `notifyConversationDataReceived:`, was added in a subclass of `ZNGConversation` that accidentally overrode the method that refreshed conversation data when a tickle was received.  Sometimes being consistent is a bad thing.

IOS-849: Fix method name collision that broke conversation tickles

---

Pod/Classes/UI/Controllers/ZNGLabelSelectViewController.m
Pod/Classes/UI/Views/Contact Editing/ZNGLabelTableViewCell.h
Pod/Classes/UI/Views/Contact Editing/ZNGLabelTableViewCell.m
Pod/Classes/UI/Views/Contact Editing/ZNGLabelTableViewCell.xib

The "add tag" UI when editing a contact was still using the old, ugly UI.

IOS-835: Use tag/segment pills instead of ugly text

---

Pod/Classes/Models/ZNGContact/ZNGContact.h
Pod/Classes/Models/ZNGContact/ZNGContact.m
Pod/Classes/UI/Controllers/ZNGInboxViewController.m

https://zingle.atlassian.net/browse/IOS-848
The inbox now uses the same logic as the conversation views when determining whether to display a locally formatted phone number value or the full, unformatted phone number (for non-local phone numbers).

IOS-848: Fixed local vs. international phone number display in inbox

---

Pod/Classes/Models/ZNGContact/ZNGContact.h
Pod/Classes/Models/ZNGContact/ZNGContact.m

The lateness (dot color) for inbox selection (team/person/my inbox menu) did not match the logic for the inbox itself (dot next to each contact name).  The inbox will now use the new `unconfirmed_at` value to match the new inbox selection behavior.

IOS-853: Use unconfirmed_at instead of last message time if possible

---

Example/Tests/TestURLParsing.m
Pod/Classes/Clients/NSURL+Zingle.h
Pod/Classes/Clients/NSURL+Zingle.m
Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/ZingleSession.m

- Put all of that code into `NSURL+Zingle` where we previously extracted the instance prefix but left forming the specific URLs up to the caller
- Add unit tests
- Become confused by how the same production auth path no longer works after the refactor even though requests going out over the wire look identical
- Become terrified when changing from `secure.zingle.me/auth` to `app.zingle.me/auth` magically fixes the problem.  I intended to make this same change after verifying that the old behavior worked after the refactor.
- Close your eyes, take a shower, and move on with your life

Refactor logic to find api/auth/socket paths

---

Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.h
Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.m
Pod/Classes/UI/Categories/UILabel+NetworkStatus.m

This allows usage of the network troubleshooting banner to show that the build is a non-production build.

Added a new network status for connected-to-non-production

---

Example/Tests/TestURLParsing.m
Pod/Classes/Clients/NSURL+Zingle.m
Pod/Classes/Clients/ZNGSocketClient.m

https://zingle.atlassian.net/browse/TECH-11983
- V2 API URL was being parsed incorrectly from a socket URL with a non-default port.  Added a unit test to reproduce this and updated the URL parsing logic to ignore port.  This bug caused the socket client to be unable to subscribe to service updates.
- After fixing the above, the code to uncover numeric IDs from socket was dead after the JWT refactor.  It has been shocked back into life.

TECH-11983: Fixed two issues breaking socket service handshake

---

Pod/Classes/Models/ZNGContact/ZNGContact.m

https://zingle.atlassian.net/browse/IOS-926
The logic to determine whether a contact has been changed since we last saw it was not considering calendar events.  Silly contact.

IOS-926: Calendar events cause contact refresh

---

Pod/Classes/ZingleAccountSession.m

https://zingle.atlassian.net/browse/IOS-908
SSO users may not have a login name per se.

IOS-908: Switch from using login name to username for analytics

---

Pod/Classes/Clients/ZNGSocketClient.m

This issue affected something like 5% of all connections, likely only occurring on socket servers that include JWT support.
__Likely related tickets:__
https://zingle.atlassian.net/browse/IOS-915
https://zingle.atlassian.net/browse/IOS-917
https://zingle.atlassian.net/browse/IOS-920
https://zingle.atlassian.net/browse/IOS-923
https://zingle.atlassian.net/browse/IOS-926
https://zingle.atlassian.net/browse/IOS-927
**Cause:** The socket server sometimes takes a full second or so to complete authentication.  The Socket IO client used by the iOS app incorrectly calls its `connect` callback when the TCP connection is established rather than waiting for the full connect response from the server (issue 1194 in https://github.com/socketio/socket.io-client-swift )
**Symptom:** All events regarding …

Detect and recover from silent failure in `bindNodeController`

---

Pod/Classes/Clients/ZNGSocketClient.m

https://zingle.atlassian.net/browse/IOS-935
Socket client was not rebinding after reconnecting due to improper retention of the relevant flag.

IOS-935: Fully recover socket connection after interruption

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

https://zingle.atlassian.net/browse/IOS-918
The original iOS bug: https://stackoverflow.com/questions/21742376/nsattributedstring-changed-font-unexpectedly-after-inserting-image
The old fix recorded the text field's font and set it back to normal after adding attributed text.  This caused a race condition in iOS 12, especially with smaller devices, that could cause unresolvable and permanent layout conflicts.  The end result was the text field staying massive forever and no longer resizing.

IOS-918: Stop angering auto layout when compensating for an iOS text field bug

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.h
Pod/Classes/UI/ViewModels/Events/ZNGConversation.m

https://zingle.atlassian.net/browse/IOS-892
The code to detect when a contact's channel has changed in order to display it in the UI was always failing if a non-message event existed between the message in question and the prior message.

IOS-892: Fix mixed detection of changing channel if non-message events exist in between

---

ZingleSDK.podspec

https://zingle.atlassian.net/browse/IOS-949
Hopefully this subspec is temporary and Apple fixes the ibtool crash

IOS-949: Use the new JSQMessages subspec to avoid haunted xibs

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/Controllers/ZNGImageAttachmentController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/ZNGConversation.storyboard
ZingleSDK.podspec

- Replaced some deprecations
- Surrounded one tricky deprecation with compiler flags to ignore #fornow
- Incremented target to iOS 11 to allow later usage of color assets

Fix warnings in newer versions of Xcode

---

Pod/Classes/Clients/ZNGJWTClient.m
Pod/Classes/ZingleAccountSession.m

- The `_requestPending` flag was not being set correctly when refreshing a JWT.
- Initial service/account fetches were dodging the normal error handling logic.  This was not intentional and caused a problem while fixing the above.

IOS-983: Less spammy JWT refresh

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/ZingleSession.m

https://zingle.atlassian.net/browse/IOS-986
These SDK changes do not actually address the above ticket, but:
1. The logging helped diagnose it
2. Fixing this issue also uncovered an issue that caused socket to forever use an expired JWT and never recover if the app was fully open and active during the entire token lifetime.  The socket connection itself is still alive, but the server silently ignores all `bindNodeController` requests with the old JWT.  This state is likely impossible with real world JWT lifetimes, but this "OK, we've failed five times, let's try a hard reconnect" logic makes socket more robust in general.

IOS-986: Add more logging during JWT refresh and fix socket recovery

---

Pod/Classes/Clients/ZNGJWTClient.m

https://zingle.atlassian.net/browse/IOS-986
It's bad form to call an async callback within the same call stack that triggered it.  This was causing timing issues in our (admittedly fragile) iOS app initial launch and login.

IOS-986: Delay async callback for JWT refresh failure

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

The conversation UI was a bit too aggressive when trying to detect channel changes and was spewing warnings from every internal note.

Quash a false positive warning log message

---

Pod/Classes/UI/Controllers/ZNGImageAttachmentController.m

Getting image data from the photo library is much more straightforward in iOS 11+, and we no longer support 10-.
Note that this build will fail due to https://github.com/Zingle/ios-sdk/pull/242

Remove deprecated `UIImagePickerControllerReferenceURL` usage

---

Example/Podfile.lock
Example/ZingleSDK.xcodeproj/project.pbxproj
Pod/Classes/UI/Controllers/ZNGImageViewController.h
Pod/Classes/UI/Controllers/ZNGImageViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.m
ZingleSDK.podspec

Migrated `SDWebImage` code since it now includes out-of-the-box GIF support without requiring `FLAnimatedImageView`

Updated SDWebImage to 5.0

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

Note: defect, so no need to JIRA
https://zingle.atlassian.net/browse/IOS-1002
Apparently setting `attributedText` blows away color settings along with fonts.  We don't want that.

IOS-990: Fix invisible template/field text in conversations

---

Pod/Classes/ZingleSession.m

This was silly.  The bundle ID was 1.1.0 and hasn't been updated in forever.

Set x-zingle-client-version to be the app bundle ID and not the SDK's

---

Pod/Classes/UI/Controllers/ZNGLabelSelectViewController.m

https://zingle.atlassian.net/browse/IOS-1015
The tint color was white when the search bar had a blue background.  In adding dark mode support, this was changed to a normal white/black background.

IOS-990: Correct search bar tint color in tag select view

---

Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

https://zingle.atlassian.net/browse/IOS-1019 (subtask, so no JIRA actions needed)
We were previously saving font/color and manually restoring them when adding text/images to `UITextField`s.  A slightly better solution is to apply the text field's `typingAttributes` to any text/image that is being added to the text field (templates, custom fields, and image attachments).  This prevents iOS from blowing away the text field's styling when adding text/images via code.
This PR makes that change and fixes one place where the manual save/restore had missed this.

IOS-1019: Fix vanishing text when inserting images/templates/contact fields

---

Pod/Classes/Clients/ZNGSocketClient.m
Pod/Classes/Clients/ZNGUserClient.h
Pod/Classes/Clients/ZNGUserClient.m
Pod/Classes/Models/ZNGUser.h
Pod/Classes/Models/ZNGUser.m
Pod/Classes/Models/ZNGUserV2.h
Pod/Classes/Models/ZNGUserV2.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

Relevant parent ticket.  Don't mash any buttons in Jira; Android needs updates as well:
https://zingle.atlassian.net/browse/TECH-13691
In the old world, user data came from socket (gross) and included online status.
In the new world, user data is requested from the V2 API.  Socket delivers IDs of online users asynchronously.
We're now better prepared to inhabit this new world.

TECH-13691: User data from v2 API instead of socket

---

Pod/Assets/ZNGColors.xcassets/ZNGInternalNoteBackground.colorset/Contents.json
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.h
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.h
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.h
Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.m
Pod/Classes/UI/Views/ZNGServiceConversationToolbarContentView.xib
Pod/Classes/UI/ZNGConversation.storyboard

https://jira.medallia.com/browse/ZIN-306
- Moved note composition from an ugly alert view to the same input text field that is used for message composition
- Wired note/message mode buttons into logic to actually toggle
- Added beautiful yellow background for note entry

ZIN-306: Toggling to and from note entry

---

Pod/Assets/ZNGColors.xcassets/ZNGInternalNoteHighlightedBackground.colorset/Contents.json
Pod/Classes/Models/ZNGEvent.h
Pod/Classes/Models/ZNGEvent.m
Pod/Classes/Models/ZNGEventMetadataEntry.h
Pod/Classes/Models/ZNGEventMetadataEntry.m
Pod/Classes/UI/Controllers/ZNGConversationViewController.h
Pod/Classes/UI/Controllers/ZNGConversationViewController.m
Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.h
Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.m
Pod/Classes/UI/Views/ZNGConversationCellOutgoing.xib
Pod/Classes/UI/Views/ZNGMessageTextView.h
Pod/Classes/UI/Views/ZNGMessageTextView.m

https://jira.medallia.com/browse/ZIN-309
- Added support for upcoming `metadata` array of mentions in events returned from the API
- Added `attributedText` getter to `ZNGEventViewModel` to provide attributed text with attributes around mentions of both users and teams, also providing some extra spacing around mentions via kern attributes
- Created subclass of `UITextField` to draw rounded highlights around mentions

ZIN-309: Mention highlighting in notes

---

Pod/Classes/UI/Categories/UITextView+TextRects.h
Pod/Classes/UI/Categories/UITextView+TextRects.m
Pod/Classes/UI/Controllers/ZNGMentionSelectionController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/UI/Views/ZNGConversationTextView.h
Pod/Classes/UI/Views/ZNGConversationTextView.m
Pod/Classes/UI/Views/ZNGMessageTextView.m

https://jira.medallia.com/browse/ZIN-308
- Moved the text coordinate code used by mention highlighting logic out of the conversation bubble text view class and into a reusable category on `UITextView`
- Update input to use the above highlighting logic
- Deletion/editing of any part of a completed mention now removes/replaces that entire mention

ZIN-308: Mention highlighting/deletion in input

---

Pod/Classes/Clients/ZNGJWTClient.h
Pod/Classes/Clients/ZNGJWTClient.m

SDK work for https://jira.medallia.com/browse/ZIN-1433
- Moved some JWT processing code into a common method
- Added support for the new API endpoint that allows exchanging an OAuth token from an arbitrary identity provider for a JWT

ZIN-1433: Add support for OAuth token exchange

---

Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m
Pod/Classes/UI/Views/ZNGEditContactFooter.xib

Handling slight behavior differences in iOS 14:
- Contact edit footer tint color now needs to be specifically set to transparent
- Date pickers must now be manually set to `.wheels` to work as `inputView`s
Small issues totally unrelated to iOS 14 but found at the same time:
- An old contact fields header was still called "custom fields"
- Header background color was wrong in light mode in the assignment view

Some cleanup for building with the iOS 14 SDK

---

Pod/Classes/ZingleAccountSession.m
Pod/Classes/ZingleSession.h
Pod/Classes/ZingleSession.m

https://jira.medallia.com/browse/ZIN-1174
The old logout also removed push notification subscriptions. Current work on idle logout demands that pushes survive.

ZIN-1174: Add an optional flag on logout to keep push notifications alive

---

Pod/Classes/UI/Controllers/ZNGAssignmentViewController.h
Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
Pod/Classes/UI/Controllers/ZNGContactEditViewController.h
Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
Pod/Classes/UI/Controllers/ZNGContactEventsViewController.h
Pod/Classes/UI/Controllers/ZNGContactEventsViewController.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.h
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Pod/Classes/ZingleAccountSession.h
Pod/Classes/ZingleAccountSession.m

https://jira.medallia.com/browse/ZIN-1174
- Add an `idleTimeLimit` property to sessions that indicates 0 for most users and 20 minutes for HIPAA users
- Lots of hiding of PHI (for HIPAA users only) when the app enters the background to prevent it showing up in the app switcher forever

ZIN-1174: Idle timeout for HIPAA users

---

Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

https://jira.medallia.com/browse/ZIN-1809
Show an ugly NO YOU DON'T modal when HIPAA users dare to attach an image.
A less ugly fix will come with the mentions release. (This toolbar code was heavily refactored from its current disaster to a modular set of buttons to support mentions.) Less ugly fix will arrive in https://jira.medallia.com/browse/ZIN-1811

ZIN-1809: Disallow image attachments for HIPAA users

---

Pod/Classes/Models/ZNGService/ZNGService.h
Pod/Classes/Models/ZNGService/ZNGService.m
Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m

https://jira.medallia.com/browse/ZIN-1809
A user who has HIPAA access should still be able to attach images when using non HIPAA services.

ZIN-1809: Disable HIPAA attachments by active service not all accessible services

---

Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m

https://jira.medallia.com/browse/ZIN-1647
- Adding support for arbitrary fields was as simple as updating the doc comment
- Added `unconfirmed_at` to inbox sorting constants

ZIN-1647: Add ability to sort inbox by arbitrary fields and unconfirmed time

---

Pod/Classes/Logging/ZNGAnalytics.m
Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m

https://jira.medallia.com/browse/ZIN-1648
Added a check to the existing `canBeUsedForSession:` on inbox data to check if contact fields used in sorting are available in the current session.

ZIN-1648: Add check for needed contact fields to existing inbox data filter availability check

---

Pod/Classes/UI/Controllers/ZNGInboxViewController.h
Pod/Classes/UI/Controllers/ZNGInboxViewController.m

If subclasses of `ZNGInboxViewController` add their own data to the table, they may need to manage it explicitly when `ZNGInboxViewController` is deleting rows via `deleteRows:`. Subclasses can override this new method to do so.

Added a public method that is called when performing animated inbox table row deletion

---

Pod/Classes/UI/Views/Contact Editing/ZNGContactDateOrTimeFieldTableViewCell.m

https://jira.medallia.com/browse/ZIN-2095
https://console.firebase.google.com/u/1/project/medallia-zingle/crashlytics/app/ios:com.zingleme.Zingle/issues/7035cc8e8e22f267e47b7a5ff4fe4bda
This was seen on a customer device running iOS 12.4.9 and was reproduced in a 12.4 simulator.

ZIN-2095: Fix setting date to nil causing a crash on older versions iOS

---

Pod/Classes/UI/Views/Contact Editing/ZNGContactTextFieldTableViewCell.m

https://jira.medallia.com/browse/ZIN-2247
It looks like text fields have been broken since https://github.com/Zingle/ios-sdk/pull/284

ZIN-2247: Fix regression that sometimes erases text contact fields

---

Pod/Classes/Clients/NSURL+Zingle.m

This is not unit tested because it's a bit wacky, depends on local Docker configuration, and has no effect on production or QA instances.

Update socket URL for local dev

---

Example/Tests/TestConversation.m
Pod/Classes/Models/ZNGParticipant.h
Pod/Classes/Models/ZNGParticipant.m
Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m

https://jira.medallia.com/browse/ZIN-2445
Previously we sent just channel value. The API just started obfuscating channel values when contact privacy is enabled. This was breaking outbound messages. Adding the ID fixes it.

ZIN-2445: Add channel ID to outbound messages

---

Example/Tests/TestAccountSession.m
Pod/Classes/ZingleAccountSession.m

https://jira.medallia.com/browse/ZIN-2484
We had updated the normal `ZNGConversation` sending but did not touch the code used by the compose message view.

ZIN-2484: Fix additional issue sending messages to phone numbers with contact privacy on

---

Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactChannelTableViewCell.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.h
Pod/Classes/UI/Views/Contact Editing/ZNGContactDefaultFieldsTableViewCell.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactEditTableViewCell.h
Pod/Classes/UI/Views/Contact Editing/ZNGContactEditTableViewCell.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactPhoneNumberTableViewCell.m
Pod/Classes/UI/Views/Contact Editing/ZNGContactSingleSelectFieldTableViewCell.m

https://jira.medallia.com/browse/ZIN-2501
There was an awkward mix of the old `applyChangesIfFirstResponder` logic and the newer `applyInProgressChanges` logic. There can be only one.
Also fixed a further regression that this caused which would save `false` for bool fields that had not actually been edited.

ZIN-2501: Fix regression saving contact field edits when "save" is hit with input still active in a text field

---

Pod/Classes/Clients/ZNGJWTClient.m
Pod/Classes/Utility/NSString+ZNGJWT.h
Pod/Classes/Utility/NSString+ZNGJWT.m
Pod/Classes/ZingleSession.m

This was a guess, at best, was causing issues with HIPAA biometric login, and now opaquely varies for standard vs. HIPAA users.
The newer JWT refreshing code now gracefully handles these errors and will work around them if possible (e.g. saved credentials exist) anyway.

Removed code that guessed at JWT full expiration time
