- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-527
> IOS-527: No more forwarding of outbound messages

- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/Views/ZNGConversationCellIncoming.m
http://jira.zinglecorp.com:8080/browse/IOS-493
> IOS-493 - Fix position of incoming image attachments

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Regression caused by https://github.com/Zingle/ios-business-app/pull/15 when implementing https://github.com/Zingle/ios-business-app/issues/12
> Fix a regression caused by avatar changes

- Pod/Classes/UI/Layout/ZNGBubblesSizeCalculator.m
Fixes https://github.com/Zingle/ios-business-app/issues/25
> Bubble size iPad orientation shenanigans

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Pod/Classes/UI/ViewModels/ZNGConversationServiceToContact.m
http://jira.zinglecorp.com:8080/browse/IOS-470
Sister PR:  https://github.com/Zingle/ios-business-app/pull/30
&nbsp;&nbsp;&nbsp;💬
☎️      ⚡️
> IOS-470: Conversation channel will no longer switch automatically

- Pod/Classes/Logging/ZNGAnalytics.h
- Pod/Classes/Logging/ZNGAnalytics.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
🥚 🥚  &nbsp;&nbsp; ➡️  &nbsp;&nbsp; ✍️
> Added easter egg Intercom events

- Example/Podfile.lock
> Updated socket client pod to get rid of Swift 3.1 warnings

- Example/Tests/TestImageAttachmentSending.m
- Example/Tests/TestMessageSending.m
- Example/Tests/mocks/ZNGMockMessageClient.h
- Example/Tests/mocks/ZNGMockMessageClient.m
- Example/Tests/mocks/ZNGStubbedEventClient.m
- Example/ZingleSDK.xcodeproj/project.pbxproj
- Pod/Classes/UI/ViewModels/ZNGConversation.m
http://jira.zinglecorp.com:8080/browse/IOS-612
💥  🔒  💥  &nbsp;&nbsp;&nbsp; ➡️  &nbsp;&nbsp;&nbsp; 🔓  &nbsp;&nbsp;&nbsp; ➡️  &nbsp;&nbsp;&nbsp; 😀
> IOS-612: Fix input buttons staying locked after sending a message

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
> Made robot eye lasers red

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-589
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⏬ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⏬ ⏬ ⏬ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⏬ ⏬ ⏬ ⏬ ⏬ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ 
⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬ ⏬
> IOS-589: Triggering an automation will now scroll down

- Pod/Classes/Logging/ZNGAnalytics.m
http://jira.zinglecorp.com:8080/browse/IOS-616
🐶  🏷
> IOS-616: UUID instead of email as Segment unique ID

- Pod/Classes/Models/ZNGContact/ZNGContact.h
- Pod/Classes/Models/ZNGContact/ZNGContact.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
..instead of only seeing your own in the inbox/settings.
📷  &nbsp;&nbsp;&nbsp; 😸
> IOS-610: Actually show user avatars in conversation

- Pod/Classes/Models/ZNGEvent.m
- Pod/Classes/UI/Layout/ZNGConversationFlowLayout.m
- Pod/Classes/UI/Views/ZNGEventCollectionViewCell.xib
http://jira.zinglecorp.com:8080/browse/IOS-617
If you like XML, then you've come to the right pull request!
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
🏃  💨
> IOS-617: Detailed event re-styling

- Example/Tests/TestAccountSession.m
- Pod/Classes/Models/ZNGUser.h
- Pod/Classes/Models/ZNGUser.m
- Pod/Classes/Models/ZNGUserAuthorization.m
Related to http://jira.zinglecorp.com:8080/browse/IOS-615
📝
> IOS-615: Consolidated logic for computing user display name 

- Pod/Classes/Models/ZNGUser.m
- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/ViewModels/ZNGConversationServiceToContact.m
http://jira.zinglecorp.com:8080/browse/IOS-538
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;✂️ 
⬜️ ⬜️ ⬜️&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⬜️ ⬜️ ⬜️ ⬜️ ⬜️ ⬜️ ⬜️ ⬜️ ⬜️ ⬜️
> IOS-538: Extra white space trimming in messages

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-635
👨‍🎨
> IOS-635: User avatars on internal notes

- Pod/Classes/UI/Views/ZNGConversationTextView.m
http://jira.zinglecorp.com:8080/browse/IOS-643
📝 😏
> IOS-643: Restored spell check action to conversation text field

- Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.h
- Pod/Classes/NetworkDiagnostics/ZNGNetworkLookout.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-642
https://fabric.io/zingle/ios/apps/com.zingleme.zingle/issues/590a059cbe077a4dcc3f5aae
KVO is the worst.
> IOS-642: Fixed a crash when rapidly changing services

- Example/Tests/TestAccountSession.m
- Pod/Classes/ZingleAccountSession.m
http://jira.zinglecorp.com:8080/browse/IOS-644
🏗 
&nbsp;🔤  👀
> IOS-644: Added alphabetic sorting to services

- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/ZNGConversation.storyboard
The only real change here is setting conversation views to hide a tab bar when presented.
> IOS-619, IOS-623: Small changes in preparation for tabs

- Pod/Classes/Models/ZNGContact/ZNGContact.h
- Pod/Classes/Models/ZNGContact/ZNGContact.m
Coming to a theater near you this spring: Initials aren't just for users.
🔥
> Initials for contacts

- Pod/Classes/UI/Controllers/ZNGInboxViewController.h
- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Moved table delegate/data source protocol declarations to header
- Stopped inbox superclass from hiding its table on load (now that we will have skeleton views)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;💀  
👈  🚦  👉 
&nbsp;&nbsp;🚤  &nbsp; 👞
> Small inbox changes

- Pod/Classes/UI/Controllers/ZNGConversationViewController.h
- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversation.h
- Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
- Pod/Classes/UI/ZNGConversation.storyboard
- ZingleSDK.podspec
http://jira.zinglecorp.com:8080/browse/IOS-650
Includes small changes from https://github.com/Zingle/ios-sdk/pull/53 , so that should be merged first.
- Added loadedInitialData flag to conversation objects that is set once the first bit of data is .. loaded
- Added shimmering skeleton view to conversation view
- Wired them together
👻❕
> Skeleton loading screen for conversations

- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/Layout/ZNGConversationFlowLayout.m
- Pod/Classes/UI/Views/ZNGConversationHeader.xib
http://jira.zinglecorp.com:8080/browse/IOS-653
Added a header above the topmost message in a conversation.  This also appears alone in empty conversations (that are now readily reachable from the new contacts page.)
👱  ⬅️
> Added “this is the start of the conversation” 

- Example/Podfile.lock
> Tiny dependency lock file update

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
> Removed an unneeded background view from inbox table

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
> Allow the inbox view controller to have an externally-set title

- Pod/Classes/UI/Controllers/ZNGInboxViewController.h
- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
..to allow for better refreshingness
> Made inbox refresh control a public property

- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
https://github.com/Zingle/ios-sdk/pull/65
http://jira.zinglecorp.com:8080/browse/IOS-511
> Fixed invisible sender name regression from #65

- Pod/Classes/Models/ZNGAutomation.m
http://jira.zinglecorp.com:8080/browse/IOS-666
👺
> IOS-666: Removed check for automation type before allowing manual triggering

- Example/Tests/TestInboxDataSet.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
http://jira.zinglecorp.com:8080/browse/IOS-669
I was never able to reproduce this crash, but the fix seems straightforward and low risk.
> IOS-669: Crash fix for incoming inbox data

- Pod/Classes/Clients/ZNGSocketClient.m
.. to the brave new world of -app DNS.
> Updated socket server address

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-673
🔥
> IOS-673: Fixed a crash related to swipe actions and skeleton cells

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/ZNGConversation.storyboard
http://jira.zinglecorp.com:8080/browse/IOS-661
Tag is more politically correct.
> IOS-661: Corrected three more old uses of 'label' instead of 'tag'

- Pod/Classes/Models/ZNGContactGroup.h
- Pod/Classes/Models/ZNGContactGroup.m
http://jira.zinglecorp.com:8080/browse/IOS-703
> IOS-703: Added default colors to contact groups

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-681
> IOS-681: Fix overlap of network status with top of conversations

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/ZNGConversation.storyboard
http://jira.zinglecorp.com:8080/browse/IOS-702
If a list of segments appears on the contact edit view but cannot be edited, is it there at all?  What does it all mean?
> IOS-702: Added segments into user details

- Example/Podfile.lock
- Example/ZingleSDK.xcodeproj/project.pbxproj
- Pod/Classes/Clients/ZNGBaseClient.m
- Pod/Classes/Clients/ZNGContactClient.m
- Pod/Classes/Models/ZNGChannel.m
- Pod/Classes/Models/ZNGContact/ZNGContact.m
- Pod/Classes/Models/ZNGContact/ZNGNewContact.m
- Pod/Classes/Models/ZNGContactField.m
- Pod/Classes/Models/ZNGContactFieldValues/ZNGContactFieldValue.m
- Pod/Classes/Models/ZNGContactFieldValues/ZNGNewContactFieldValue.m
- Pod/Classes/Models/ZNGContactGroup.m
- Pod/Classes/Models/ZNGContactService.m
- Pod/Classes/Models/ZNGCorrespondent.m
- Pod/Classes/Models/ZNGEvent.m
- Pod/Classes/Models/ZNGFieldOption.m
- Pod/Classes/Models/ZNGMessage/ZNGMessage.m
- Pod/Classes/Models/ZNGMessage/ZNGMessageForwardingRequest.m
- Pod/Classes/Models/ZNGMessage/ZNGNewMessage.m
- Pod/Classes/Models/ZNGService/ZNGNewService.m
- Pod/Classes/Models/ZNGService/ZNGService.m
- Pod/Classes/Models/ZNGSetting.h
- Pod/Classes/Models/ZNGSetting.m
- Pod/Classes/Models/ZNGSettingsField.m
- Pod/Classes/ValueTransformers/ZingleValueTransformers.m
- ZingleSDK.podspec
An old version was used due to a conflict with an old client's code.  Back to the future we go.
This PR may be easier to follow commit-by-commit instead of one lump of changes.
> Update Mantle (JSON mapping framework)

- Example/Podfile.lock
- ZingleSDK.podspec
No actual code changes were necessary.  What a boring pull request.
> Updated CocoaLumberjack dependency

- Example/Podfile.lock
- Pod/Classes/Clients/ZNGBaseClient.m
- Pod/Classes/Clients/ZNGHotsosClient.m
- Pod/Classes/Clients/ZNGSocketClient.m
- Pod/Classes/ZingleSession.m
- ZingleSDK.podspec
> Update networking library

- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
Small SDK change to allow IOS-715's larger business app changes.
> IOS-715: Added a method to test push notifications

- Pod/Classes/UI/Views/ZNGConversationTextView.m
- Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.m
- Pod/Classes/UI/Views/ZNGServiceConversationToolbarContentView.xib
> IOS-677: Adjusted spacing and positioning of input toolbar elements

- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
I hate implicit capture lists.
> Fixed a retain cycle memory leak that has been around for quite awhile

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
http://jira.zinglecorp.com:8080/browse/IOS-731
How many avatars does one man need?  Not that many.
> IOS-731: Cleaned up avatar logic to prevent avatar spam

- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
One step of many toward solving https://zingle.atlassian.net/browse/IOS-737
> Added a flag to indicate that the user's credentials have been verified at some point in the past

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
- Pod/Classes/UI/Views/ZNGConversationTypingIndicatorCell.h
- Pod/Classes/UI/Views/ZNGConversationTypingIndicatorCell.m
You shouldn't always be white, you silly dots.
> Internal note typing indicator dot color

- Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m
https://zingle.atlassian.net/browse/IOS-755
UIDatePickers in time selection mode tend to disable themselves for mysterious reasons when their date value or time zone value are changed.
Added some ugly fixes to prevent this date picker suicide.
> IOS-755: Several scary changes to solve problems with iOS 11 time pickers

- Pod/Classes/Models/ZNGService/ZNGService.h
- Pod/Classes/Models/ZNGService/ZNGService.m
- Pod/Classes/Models/ZNGTeam.h
- Pod/Classes/Models/ZNGTeam.m
Also added `- (BOOL) allowsAssignment` and `- (BOOL) allowsTeamAssignment` to `ZNGService`
> Added some teamness and featureness to service objects

- Pod/Classes/Models/ZNGService/ZNGService.h
- Pod/Classes/Models/ZNGService/ZNGService.m
- Pod/Classes/Models/ZNGTeam.h
- Pod/Classes/Models/ZNGTeam.m
- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
Some day we will get enough data to return all teams for admin/manager type dudes.
> Added filtered list of teams for relevance to current user

- Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
- Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
Adds inbox data set filters for assignment by user, assignment by team, and being unassigned.
> Assignment filtering

- Pod/Classes/Clients/ZNGContactClient.h
- Pod/Classes/Clients/ZNGContactClient.m
- Pod/Classes/Models/ZNGContact/ZNGContact.h
- Pod/Classes/Models/ZNGContact/ZNGContact.m
- Pod/Classes/Models/ZNGContact/ZNGContactAssignment.h
- Pod/Classes/Models/ZNGContact/ZNGContactAssignment.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
Also replaced conversation title with a multiline label in preparation for current assignment UI, though it is not yet in place.
> Added assignment to SDK

- Pod/Classes/Models/ZNGEvent.h
- Pod/Classes/Models/ZNGEvent.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
This also includes both https://github.com/Zingle/ios-sdk/pull/134 and https://github.com/Zingle/ios-sdk/pull/135 commits until someone merges those and kicks Github into the current day.
> Added assignment events to conversation display

- Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
The loading flag was preventing the reload from succeeding.
> Clear loading flag before attempting error recovery reload

- Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
From some kind of disagreement between https://github.com/Zingle/ios-sdk/pull/135/ and https://github.com/Zingle/ios-sdk/pull/137/
> Fixed ZNGUserAuthorization/ZNGUser merge issue

- Pod/Classes/UI/ViewModels/Inbox Badges/ZNGInboxStatistician.m
> Protect against null stats data when calculating summed stats

- Pod/Classes/UI/ViewModels/Inbox Badges/ZNGInboxStatistician.m
> Oh, right, that thing can be nil, too.

- Pod/Classes/UI/Controllers/ZNGAssignmentViewController.h
- Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
- Pod/Classes/UI/ZNGConversation.storyboard
- Added search
- Adjusted header display in assignment view
- Changed wording in view header from "Assign to name" to "Assign name"
> Added searching to assignment view

- Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.h
- Pod/Classes/UI/ViewModels/Contacts/ZNGContactDataSetBuilder.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
A corresponding business app PR will use this to save/load inbox types between sessions.
> Added the ability to serialize types of inbox data sets for later restoration

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
> Silly change to greatly decrease edit contact view load time

- Pod/Classes/Models/ZNGInboxStatsEntry.m
> Fixed an integer size warning that probably only happens on 32 bit/profiling

- Pod/Classes/UI/Views/Contact Editing/ZNGContactEditFloatLabeledTextField.m
- Pod/Classes/UI/Views/ZNGNonLeakingTextField.h
- Pod/Classes/UI/Views/ZNGNonLeakingTextField.m
- Pod/Classes/UI/ZNGConversation.storyboard
Previously merged in https://github.com/Zingle/ios-sdk/pull/138
> Cherry-picked the fix from develop to prevent UITextFields from leaking themselves

- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
This was previously merged into develop in https://github.com/Zingle/ios-sdk/pull/130
> Cherry-pick a fix for network connectivity problems breaking things

- Pod/Classes/ZingleSession.m
Support the new version of `application:didReceiveRemoteNotification:` as well as the relevant `UNUserNotificationCenterDelegate` method.  You can't hide your push notifications from us forever.
> IOS-774: Updated push notification swizzling 

- Pod/Classes/UI/ZNGConversation.storyboard
- Pod/Classes/ZingleSession.m
No new code here, just bringing https://github.com/Zingle/ios-sdk/pull/151 into develop.
> Merging release into develop

- Pod/Classes/Clients/ZNGBaseClient.m
- Pod/Classes/Clients/ZNGHotsosClient.m
- Pod/Classes/Clients/ZNGSocketClient.m
- Pod/Classes/Clients/ZNGTeamClient.m
- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/Controllers/ZNGForwardingViewController.m
- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
- Pod/Classes/UI/Layout/ZNGImageAttachment.m
- Pod/Classes/UI/Layout/ZNGImageSizeCache.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversationContactToService.m
- Pod/Classes/UI/ViewModels/Inbox Badges/ZNGInboxStatistician.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m
- Pod/Classes/ZingleAccountSession.m
- Pod/Classes/ZingleContactSession.m
Cocoapods would like to enable this warning and drown all of us in yellow exclamation marks.  We can do our part to bail out.
> Replaced a billion implicit self captures to be explicit

- Pod/Classes/Models/ZNGService/ZNGService.h
- Pod/Classes/Models/ZNGService/ZNGService.m
You know, like some kind of smart person.
> Return 0 teams from the ZNGService teams getter if the teams feature is not present

- Pod/Classes/UI/ZNGConversation.storyboard
> IOS-778: Fixed accidental cropping of locked contact banner

- Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
> Stopped the keyboard from obscuring search results in assignment view

- Pod/Classes/Logging/ZNGAnalytics.h
- Pod/Classes/Logging/ZNGAnalytics.m
- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
> Added Segment events for assignment

- Pod/Classes/UI/Controllers/ZNGInboxViewController.h
- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
- Pod/Classes/UI/ZNGConversation.storyboard
- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
> Contact assignment via magical swipe action

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
https://zingle.atlassian.net/browse/IOS-784
No more secret swiping.
> IOS-784: Added Segment events to swipe assignment actions

- Pod/Classes/ZingleAccountSession.m
> IOS-792: Teammates are now sorted by active status before alphabetically

- Pod/Classes/UI/Controllers/ZNGAssignmentViewController.m
- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
> IOS-794: Fixed silly font size usage in tiny initials avatars

- Pod/Classes/Clients/ZNGSocketClient.m
- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
https://zingle.atlassian.net/browse/IOS-804
> IOS-804: Contacts appearing and disappearing now trigger refresh

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
https://zingle.atlassian.net/browse/IOS-809
You can't swipe assign if you don't have assignments.  Derp.
> IOS-809: Stop allowing nonsense swiping

- Pod/Classes/Clients/ZNGNotificationSettingsClient.h
- Pod/Classes/Clients/ZNGNotificationSettingsClient.m
- Pod/Classes/Models/ZNGNotificationSettings.h
- Pod/Classes/Models/ZNGNotificationSettings.m
- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
https://zingle.atlassian.net/browse/IOS-788
This change allows reading/writing a user's notification preferences.
> IOS-788: Added ZNGNotificationSettings and ZNGNotificationSettingsClient

- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.m
> Fixed retain cycles in inbox data that caused the data to leak forever

- Pod/Classes/UI/ViewModels/Events/ZNGEventViewModel.m
Fixes https://www.fabric.io/zingle/ios/apps/com.zingleme.zingle/issues/5a3c42408cb3c2fa6365b479
> Prevent NSNull attachmentName

- Pod/Classes/Models/ZNGService/ZNGService.m
> Disable assignment/teams for 3.0.0 release

- Pod/Classes/Models/ZNGService/ZNGService.m
> Bring back the teams

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
> IOS-858: Stopped filtering templates by type

- Pod/Classes/Models/ZNGChannel.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
https://zingle.atlassian.net/browse/IOS-857
> IOS-857: Stopped showing a redundant channel value (thanks to an API bug)

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
- Tweaked distance required for close/open swipe to better coexist with "Assign"
- Added haptic feedback when a swipe action is fully expanded
> IOS-859: Tweaks to inbox swipe actions

- Pod/Classes/UI/Controllers/ZNGInboxViewController.m
> Added warning suppression for a useless clang availability warning

- Pod/Classes/Models/ZNGMessage/ZNGNewMessage.h
- Pod/Classes/Models/ZNGMessage/ZNGNewMessage.m
- Pod/Classes/UI/Controllers/ZNGConversationViewController.h
- Pod/Classes/UI/Controllers/ZNGConversationViewController.m
- Pod/Classes/UI/Controllers/ZNGImageAttachmentController.h
- Pod/Classes/UI/Controllers/ZNGImageAttachmentController.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversation.m
- Pod/Classes/UI/Views/ZNGNewMessageInputToolbar.m
- Pod/Classes/UI/Views/ZNGNewMessageToolbarContentView.xib
- Pod/Classes/ZingleAccountSession.h
- Pod/Classes/ZingleAccountSession.m
- Moved image attaching UI code out of the conversation view controller and into a reusable class
- Added an image attachment parameter to compose new message method
> Improved image attachment support

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactPhoneNumberTableViewCell.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactPhoneNumberTableViewCell.m
- Pod/Classes/UI/ZNGConversation.storyboard
https://zingle.atlassian.net/browse/IOS-863
> IOS-863: Remove phone number types

- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
The images were still being sent but were invisible to the user after inserting a template.
> IOS-867: Stopped template insertion from hiding attached images

- Pod/Classes/UI/Transitions/ZNGEditContactTransition.m
> IOS-862: Handle identically named contact and assignee

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/ViewModels/Events/ZNGConversationServiceToContact.m
> IOS-848: Stop formatting non-local phone numbers as if they were local

- Example/Podfile.lock
- Example/ZingleSDK.xcodeproj/project.pbxproj
Come on, Cocoapods; don't do me like that.
> Update SDK test project's Cocoapods version

- Pod/Classes/Models/ZNGError.h
- Pod/Classes/Models/ZNGError.m
https://zingle.atlassian.net/browse/IOS-865
> IOS-865: Added method to ZNGError to detect an unverified email

- Example/Podfile.lock
> Updated Cocoapods to fix a build issue in iOS 12 hotfix

- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/ZNGConversation.storyboard
https://zingle.atlassian.net/browse/IOS-944
> IOS-944: Fix broken modal card presentations in iOS 13

- Pod/Classes/Clients/ZNGSocketClient.h
- Pod/Classes/Clients/ZNGSocketClient.m
> Added a parameter to socket client to allow user-agent spoofing

- Pod/Classes/UI/ZNGConversation.storyboard
https://zingle.atlassian.net/browse/IOS-940
> IOS-940: Stop overlapping names/buttons when editing a contact

- .gitmodules
- Example/Podfile
- Example/Podfile.lock
... to fix builds in Xcode 11.
> Pointed example project at local fork of JSQMessagesViewController

- Pod/Classes/UI/Controllers/ZNGImageViewController.xib
This is a regression from https://github.com/Zingle/ios-sdk/pull/244
> Fixed full image preview of animated GIFs

- Pod/Classes/Clients/ZNGJWTClient.m
> Fixed a typo in a log message

- Pod/Classes/UI/Views/ZNGTableViewCell.xib
Note: This is a defect and not the IOS-990 ticket itself, so no need to JIRA anything.
https://zingle.atlassian.net/browse/IOS-1000
> IOS-990: Fixed highlight coloring

- Example/Tests/TestAccountSession.m
- Example/Tests/TestContactSession.m
- Example/Tests/mocks/ZNGMockNotificationsClient.h
- Example/Tests/mocks/ZNGMockNotificationsClient.m
- Example/ZingleSDK.xcodeproj/project.pbxproj
- Example/ZingleSDK/ContactServiceChoosingViewController.m
- Pod/Classes/Utility/NSData+HexString.h
- Pod/Classes/Utility/NSData+HexString.m
- Pod/Classes/ZingleSDK.h
- Pod/Classes/ZingleSDK.m
- Pod/Classes/ZingleSession.h
- Pod/Classes/ZingleSession.m
https://jira.medallia.com/browse/ZIC-61
- Deprecated APNS token setting
- Added Firebase FCM token setting
- Added a unit test to unsubscribe from APNS notifications when transitioning to Firebase
- Cleaned up some tests
> RIP APNS push notifications, long live Firebase notifications

- Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.m
instead of the send icon
https://jira.medallia.com/browse/ZIN-305
> ZIN-305: "Forward" for the forward button

- Pod/Classes/UI/Views/ZNGServiceConversationToolbarContentView.xib
> Update the order of message toolbar icons

- Pod/Classes/UI/Views/ZNGServiceConversationInputToolbar.m
> Activate the keyboard when the message or note toolbar button is pressed

- Pod/Classes/Clients/NSURL+Zingle.h
- Pod/Classes/Clients/NSURL+Zingle.m
> Added web app and custom scheme URL constants to NSURL extension

- Example/Podfile.lock
- Pod/Classes/Clients/ZNGBaseClient.m
- Pod/Classes/Clients/ZNGHotsosClient.m
- Pod/Classes/Clients/ZNGIDPClient.m
- Pod/Classes/Clients/ZNGJWTClient.m
- Pod/Classes/Clients/ZNGNotificationSettingsClient.m
- Pod/Classes/Clients/ZNGSocketClient.m
- Pod/Classes/Clients/ZNGUserClient.m
- Pod/Classes/ZingleSession.m
- ZingleSDK.podspec
- Update to new major version of AFNetworking (4)
- Update all GET/POST/etc. calls for the updated method signatures in 4.x
- Specify specific major versions for all other public dependencies in the podspec
- Minor version updates for several other dependencies in the example/test app
> Update AFNetworking and some other dependencies

- Pod/Classes/Utility/NSString+ZNGJWT.h
- Pod/Classes/Utility/NSString+ZNGJWT.m
https://jira.medallia.com/browse/ZIN-1174
> ZIN-1174: Add flags for staff users and HIPAA users in JWT parsing code

- Pod/Classes/Models/ZNGContactField.h
- Pod/Classes/Models/ZNGContactField.m
- Pod/Classes/UI/Controllers/ZNGContactEditViewController.m
- Pod/Classes/UI/ViewModels/Contacts/ZNGInboxDataSet.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactCustomFieldTableViewCell.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactDateOrTimeFieldTableViewCell.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactDateOrTimeFieldTableViewCell.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactDateOrTimeInputManager.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactDateOrTimeInputManager.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactSingleSelectFieldTableViewCell.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactSingleSelectFieldTableViewCell.m
- Pod/Classes/UI/Views/Contact Editing/ZNGContactTextFieldTableViewCell.h
- Pod/Classes/UI/Views/Contact Editing/ZNGContactTextFieldTableViewCell.m
- Pod/Classes/UI/ZNGConversation.storyboard
https://jira.medallia.com/browse/ZIN-1552
- Add support for `datetime` contact field type
- Add support for `anniversary` contact field type
- Refactor contact field table cell UI class into several subclasses
> ZIN-1552: Datetime field view/edit support with some contact field UI refactors

- Pod/Classes/Logging/ZNGAnalytics.h
- Pod/Classes/Logging/ZNGAnalytics.m
https://jira.medallia.com/browse/ZIN-1666
> ZIN-1666: Add analytics tracking methods for inbox sorting/filtering

- bitrise.yml
> Add bitrise.yml config to repo

- Pod/Classes/Models/ZNGNotificationSettings.h
- Pod/Classes/Models/ZNGNotificationSettings.m
Added "Notification when Mentions of you" setting.
> ZIN-801 [iOS] Update mobile notification settings to include "Mentions' option

- Pod/Classes/Clients/ZNGJWTClient.h
> Move JWT client methods into a protocol for more testability

- Example/Tests/TestAttributedStringMentions.m
- Pod/Classes/Logging/ZNGAnalytics.h
- Pod/Classes/Logging/ZNGAnalytics.m
- Pod/Classes/UI/Controllers/ZNGServiceToContactViewController.m
- Pod/Classes/UI/ViewModels/Events/NSAttributedString+Mentions.h
- Pod/Classes/UI/ViewModels/Events/NSAttributedString+Mentions.m
The event will be called "Mention" and we'll have a specific trait called "Source" with the of either "team" or "user".
> ZIN-2444: Add Segment analytics events for mentions actions

- Example/Tests/TestURLParsing.m
- Pod/Classes/Clients/NSURL+Zingle.m
Conversions and Unit test for new URL patterns.
> ZIN-1853: Switch environments on mobile apps
